#!/usr/bin/env bash
matches=$(git diff --staged | grep '^+' | grep -i 'wipwip')

if [ ! -z "$matches" ]
then
	cat <<\EOT
Error: Words from the blacklist were present in the diff:
EOT
	echo $matches
	exit 1
fi
exit 0
